services:
  api:
    build: .                       # builds from your Dockerfile in the repo root
    container_name: bookstore-api
    ports:
      - "8080:8080"
    environment:
      # IMPORTANT: include user/pass and point to the 'bookstore' DB; auth happens against 'admin'
      SPRING_DATA_MONGODB_URI: mongodb://rootuser:rootpass@mongodb:27017/bookstore?authSource=admin
      # (Optional) Spring profile or JVM flags:
      # SPRING_PROFILES_ACTIVE: docker
      # JAVA_OPTS: -XX:MaxRAMPercentage=75.0
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongodb:27017/?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
